# Generated by Django 6.0.7 on 2026-07-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Назва"),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Назва"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("own", "Моя схема"),
                            ("purchased", "Куплена схема"),
                            ("free", "Безкоштовна схема"),
                        ],
                        max_length=20,
                        verbose_name="Джерело",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("jewelry", "Прикраси"),
                            ("flowers", "Квіти"),
                            ("toys", "Іграшки"),
                            ("keychains", "Брелоки"),
                            ("decor", "Декор"),
                            ("accessories", "Аксесуари"),
                            ("clothes", "Одяг"),
                            ("other", "Інше"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Категорія",
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Підкатегорія"
                    ),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=150, verbose_name="Автор"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Початковий рівень"),
                            ("intermediate", "Середній рівень"),
                            ("advanced", "Складний рівень"),
                        ],
                        max_length=20,
                        verbose_name="Складність",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Планую"),
                            ("in_progress", "У роботі"),
                            ("completed", "Завершено"),
                            ("archived", "Архів"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Опис")),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, upload_to="schemes/pdfs/", verbose_name="PDF-файл"
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        upload_to="schemes/images/",
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="Обране"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="schemes",
                        to="schemes.tag",
                        verbose_name="Теги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Схема",
                "verbose_name_plural": "Схеми",
                "ordering": ["-created_at"],
            },
        ),
    ]
