# Generated by Django 6.0.7 on 2026-07-28 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemes", "0001_initial"),
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schemes",
                to="telegram_bot.telegramuser",
                verbose_name="Власник",
            ),
        ),
        migrations.AddField(
            model_name="scheme",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Загальнодоступна"),
                    ("private", "Приватна"),
                    ("moderation", "На модерації"),
                    ("rejected", "Відхилена"),
                ],
                db_index=True,
                default="public",
                max_length=20,
                verbose_name="Доступність",
            ),
        ),
    ]
