# Generated by Django 6.0.7 on 2026-07-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemes", "0002_scheme_owner_scheme_visibility"),
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemeFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Додано в обране"
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_records",
                        to="schemes.scheme",
                        verbose_name="Схема",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_favorites",
                        to="telegram_bot.telegramuser",
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обрана схема",
                "verbose_name_plural": "Обрані схеми",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "scheme"), name="unique_user_scheme_favorite"
                    )
                ],
            },
        ),
    ]
