# Generated by Django 6.0.7 on 2026-07-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schemes", "0003_schemefavorite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheme",
            name="is_favorite",
        ),
    ]
