# Generated by Django 6.0.7 on 2026-07-25 17:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schemes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Назва"),
                ),
            ],
            options={
                "verbose_name": "Тип матеріалу",
                "verbose_name_plural": "Типи матеріалів",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Назва"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Виробник"
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Артикул",
                    ),
                ),
                (
                    "color_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Назва кольору"
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Код кольору"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "шт."),
                            ("gram", "г"),
                            ("meter", "м"),
                            ("centimeter", "см"),
                            ("package", "упаковка"),
                        ],
                        default="piece",
                        max_length=20,
                        verbose_name="Одиниця вимірювання",
                    ),
                ),
                (
                    "quantity_in_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Залишок на складі",
                    ),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Мінімальний запас",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примітки")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "material_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="materials.materialtype",
                        verbose_name="Тип матеріалу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Матеріал",
                "verbose_name_plural": "Матеріали",
                "ordering": ("material_type__name", "name", "color_name"),
            },
        ),
        migrations.CreateModel(
            name="SchemeMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Необхідна кількість",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Примітка"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheme_requirements",
                        to="materials.material",
                        verbose_name="Матеріал",
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_requirements",
                        to="schemes.scheme",
                        verbose_name="Схема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Матеріал схеми",
                "verbose_name_plural": "Матеріали схем",
                "ordering": ("scheme__title", "material__name"),
            },
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.UniqueConstraint(
                fields=(
                    "name",
                    "material_type",
                    "manufacturer",
                    "article",
                    "color_code",
                ),
                name="unique_material_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemematerial",
            constraint=models.UniqueConstraint(
                fields=("scheme", "material"), name="unique_material_for_scheme"
            ),
        ),
    ]
