# Generated by Django 6.0.7 on 2026-07-25 19:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
        ("schemes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("receipt", "Надходження"), ("write_off", "Списання")],
                        max_length=20,
                        verbose_name="Тип операції",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Кількість",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Залишок після операції",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Примітка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата операції"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рух матеріалу",
                "verbose_name_plural": "Рух матеріалів",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.AlterModelOptions(
            name="schemematerial",
            options={
                "ordering": ("material__name", "material__color_name"),
                "verbose_name": "Матеріал схеми",
                "verbose_name_plural": "Матеріали схем",
            },
        ),
        migrations.RemoveConstraint(
            model_name="material",
            name="unique_material_variant",
        ),
        migrations.RemoveConstraint(
            model_name="schemematerial",
            name="unique_material_for_scheme",
        ),
        migrations.AddField(
            model_name="materialtype",
            name="description",
            field=models.TextField(blank=True, verbose_name="Опис"),
        ),
        migrations.AddField(
            model_name="schemematerial",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Створено",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schemematerial",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
        ),
        migrations.AlterField(
            model_name="material",
            name="article",
            field=models.CharField(blank=True, max_length=100, verbose_name="Артикул"),
        ),
        migrations.AlterField(
            model_name="material",
            name="color_code",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Код кольору"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=150, verbose_name="Виробник"),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="material",
            name="quantity_in_stock",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Кількість на складі",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "г"),
                    ("pcs", "шт."),
                    ("m", "м"),
                    ("cm", "см"),
                    ("pack", "уп."),
                    ("set", "набір"),
                ],
                default="g",
                max_length=20,
                verbose_name="Одиниця вимірювання",
            ),
        ),
        migrations.AlterField(
            model_name="materialtype",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Назва типу"
            ),
        ),
        migrations.AlterField(
            model_name="schemematerial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scheme_requirements",
                to="materials.material",
                verbose_name="Матеріал",
            ),
        ),
        migrations.AddConstraint(
            model_name="schemematerial",
            constraint=models.UniqueConstraint(
                fields=("scheme", "material"), name="unique_material_per_scheme"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="materials.material",
                verbose_name="Матеріал",
            ),
        ),
    ]
