# Generated by Django 6.0.7 on 2026-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_stockmovement_alter_schemematerial_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(
                choices=[
                    ("gram", "г"),
                    ("piece", "шт."),
                    ("meter", "м"),
                    ("centimeter", "см"),
                    ("pack", "уп."),
                    ("set", "набір"),
                ],
                default="gram",
                max_length=20,
                verbose_name="Одиниця вимірювання",
            ),
        ),
    ]
