# Generated by Django 6.0.7 on 2026-08-06 06:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_material_unit"),
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMaterialStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_in_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Кількість на складі",
                    ),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Мінімальний запас",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примітки")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_stocks",
                        to="materials.material",
                        verbose_name="Матеріал",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_stocks",
                        to="telegram_bot.telegramuser",
                        verbose_name="Власник складу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персональний запас",
                "verbose_name_plural": "Персональні запаси",
                "ordering": ("owner_id", "material_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "material"), name="unique_user_material_stock"
                    )
                ],
            },
        ),
    ]
