# Generated by Django 6.0.7 on 2026-09-04 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_usermaterialstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_movements",
                to="materials.usermaterialstock",
                verbose_name="Персональний запас",
            ),
        ),
    ]
