# Generated by Django 6.0.7 on 2026-07-25 21:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0003_alter_material_unit"),
        ("schemes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Кількість виробів",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Заплановано"),
                            ("in_progress", "У роботі"),
                            ("completed", "Завершено"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примітки")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Розпочато"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершено"
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="schemes.scheme",
                        verbose_name="Схема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Виробниче завдання",
                "verbose_name_plural": "Виробничі завдання",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="ProductionMaterialUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(max_length=200, verbose_name="Назва матеріалу"),
                ),
                (
                    "article",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Артикул"
                    ),
                ),
                (
                    "color_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Колір"),
                ),
                (
                    "unit_label",
                    models.CharField(max_length=30, verbose_name="Одиниця вимірювання"),
                ),
                (
                    "required_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Списана кількість",
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Залишок до списання",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Залишок після списання",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата списання"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_usages",
                        to="materials.material",
                        verbose_name="Матеріал",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_usages",
                        to="production.productionorder",
                        verbose_name="Виробниче завдання",
                    ),
                ),
            ],
            options={
                "verbose_name": "Матеріал виробництва",
                "verbose_name_plural": "Матеріали виробництва",
                "ordering": ("material_name", "color_name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("production", "material"),
                        name="unique_material_per_production",
                    )
                ],
            },
        ),
    ]
