# Generated by Django 6.0.7 on 2026-07-25 20:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0003_alter_material_unit"),
        ("schemes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активний"),
                            ("ordered", "Замовлення оформлено"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_carts",
                        to="schemes.scheme",
                        verbose_name="Схема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кошик",
                "verbose_name_plural": "Кошики",
                "ordering": ("-updated_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=150, verbose_name="Ім’я отримувача"),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Електронна пошта"
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="Адреса доставки"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Коментар")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Нове"),
                            ("confirmed", "Підтверджено"),
                            ("completed", "Виконано"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата оформлення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to="shop.cart",
                        verbose_name="Кошик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_name",
                    models.CharField(max_length=200, verbose_name="Назва матеріалу"),
                ),
                (
                    "article",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Артикул"
                    ),
                ),
                (
                    "color_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Колір"),
                ),
                (
                    "unit_label",
                    models.CharField(max_length=30, verbose_name="Одиниця вимірювання"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Кількість",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="materials.material",
                        verbose_name="Матеріал",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                        verbose_name="Замовлення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиція замовлення",
                "verbose_name_plural": "Позиції замовлення",
                "ordering": ("material_name", "color_name"),
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Кількість для придбання",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.cart",
                        verbose_name="Кошик",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cart_items",
                        to="materials.material",
                        verbose_name="Матеріал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиція кошика",
                "verbose_name_plural": "Позиції кошика",
                "ordering": ("material__name", "material__color_name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cart", "material"), name="unique_material_per_cart"
                    )
                ],
            },
        ),
    ]
